const DB_URL='./data/database.json';
const STORAGE_KEY='pl-commentary-bank-db-v1';
let db=null;
let selectedId=null;
let dataOrigin='remote';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const mark=g=>({'道内':'●','広域/選考':'◆','全国':'★','国際':'✦'}[g]||'●');
const eventClass=t=>t==='三種PL'?'pl':'bp';
const attempt=s=>esc(s).replaceAll('×','<span class="fail">×</span>');
const nowDate=()=>new Date().toISOString().slice(0,10);
const save=()=>{db.meta.updatedAt=nowDate();db.meta.localSavedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(db,null,2));dataOrigin='local';render();};
const download=(name,text,type='application/json')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);};
async function fetchRemoteDb(){const res=await fetch(`${DB_URL}?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error('正本DBを読み込めませんでした');return res.json();}
async function load(){const local=localStorage.getItem(STORAGE_KEY);if(local){db=JSON.parse(local);dataOrigin='local';}else{db=await fetchRemoteDb();dataOrigin='remote';}selectedId=db.players[0]?.id;render();}
async function reloadRemote(){if(!confirm('GitHub Pages上の正本DBを再読込します。ブラウザ内のローカル編集は上書きされます。続けますか？'))return;db=await fetchRemoteDb();localStorage.setItem(STORAGE_KEY,JSON.stringify(db,null,2));dataOrigin='remote';selectedId=db.players[0]?.id;render();}
async function discardLocal(){if(!confirm('ブラウザ内のローカル編集を破棄し、正本DBを読み直します。続けますか？'))return;localStorage.removeItem(STORAGE_KEY);db=await fetchRemoteDb();dataOrigin='remote';selectedId=db.players[0]?.id;render();}
function player(){return db.players.find(p=>p.id===selectedId)||db.players[0];}
function playerText(p){return [p.group,p.lot,p.name,p.kana,p.team,p.bodyweightClass,p.entryDivision].join(' ').toLowerCase();}
function renderList(){const q=$('#search').value.toLowerCase();$('#playerList').innerHTML=db.players.filter(p=>playerText(p).includes(q)).sort((a,b)=>String(a.group).localeCompare(b.group)||a.lot-b.lot).map(p=>`<li><button data-id="${p.id}"><strong>${p.group}.Lot ${p.lot}</strong> ${esc(p.name)} ${esc(p.kana)}<br><small>${esc(p.team)} / ${esc(p.bodyweightClass)}</small></button></li>`).join('');document.querySelectorAll('#playerList button').forEach(b=>b.onclick=()=>{selectedId=b.dataset.id;render();});}
const fields=[['group','グループ'],['lot','Lot'],['name','氏名'],['kana','フリガナ'],['englishName','英字名'],['sex','性別'],['bodyweightClass','階級'],['team','所属'],['entryDivision','種目'],['declaredBest','申告/参考ベスト'],['readout','読み上げ一言','textarea'],['previousFlow','前々回→前回','textarea'],['progressComment','推移コメント','textarea']];
function renderPlayerForm(){const p=player();$('#playerForm').innerHTML=fields.map(([k,label,type])=>`<label>${label}${type==='textarea'?`<textarea name="${k}" rows="3">${esc(p[k])}</textarea>`:`<input name="${k}" value="${esc(p[k])}">`}</label>`).join('')+'<button>選手データを保存</button>';$('#playerForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);for(const [k] of fields)p[k]=k==='lot'?Number(fd.get(k)):String(fd.get(k)||'');save();};}
const hFields=[['date','大会日'],['competitionName','大会正式名称'],['grade','グレード'],['eventType','種目'],['ageDivision','年齢区分'],['className','階級'],['bw','BW'],['sqAttempts','SQ試技'],['sqBest','SQベスト'],['bpAttempts','BP試技'],['bpBest','BPベスト'],['dlAttempts','DL試技'],['dlBest','DLベスト'],['total','T'],['place','順位'],['recordNote','記録メモ'],['status','確認状態'],['sourceUrl','確認元URL']];
function renderHistoryForm(){const opts={grade:['道内','広域/選考','全国','国際'],eventType:['三種PL','S-BP','EQ-BP','その他'],status:['確認済','本人申告','要再確認','未確認']};$('#historyForm').innerHTML=hFields.map(([k,label])=>{if(opts[k])return `<label>${label}<select name="${k}">${opts[k].map(o=>`<option>${o}</option>`).join('')}</select></label>`;return `<label>${label}<input name="${k}"></label>`;}).join('')+'<button>出場歴を追加</button>';$('#historyForm').onsubmit=e=>{e.preventDefault();const p=player();const fd=new FormData(e.currentTarget);const h={id:`${p.id}-h-${Date.now()}`,sourceIds:[]};for(const [k] of hFields){const v=String(fd.get(k)||'');if(k==='sourceUrl'&&v){const sid=`src-${Date.now()}`;db.sources.push({id:sid,title:v,url:v,sourceType:'その他',checkedAt:nowDate(),memo:'PWAから追加'});h.sourceIds=[sid];}else h[k]=v;}p.histories.push(h);save();e.currentTarget.reset();};}
function eventLines(h){const a=[];if(h.bw)a.push(`BW${esc(h.bw)}kg`);if(h.sqAttempts||h.sqBest)a.push(`SQ ${attempt(h.sqAttempts)}${h.sqBest?'='+esc(h.sqBest):''}`);if(h.bpAttempts||h.bpBest)a.push(`BP ${attempt(h.bpAttempts)}${h.bpBest?'='+esc(h.bpBest):''}`);if(h.dlAttempts||h.dlBest)a.push(`DL ${attempt(h.dlAttempts)}${h.dlBest?'='+esc(h.dlBest):''}`);if(h.total)a.push(`T ${esc(h.total)}`);if(h.recordNote)a.push(`記録: ${esc(h.recordNote)}`);if(h.status&&h.status!=='確認済')a.push(`確認状態: ${esc(h.status)}`);return a.map(x=>`<div>${x}</div>`).join('');}
function place(h){return h.place?` / <span class="place">${esc(h.place)}位</span>`:'';}
function card(h,i){return `<article class="event ${eventClass(h.eventType)}"><div class="event-title">${i+1}${esc(h.date)} ${esc(h.competitionName)}</div><div class="event-sub">${esc(h.eventType)}｜${esc(h.ageDivision||'')}｜${esc(h.className)}${place(h)}</div><div class="rule"></div><div class="lines">${eventLines(h)}</div><div class="badge">${mark(h.grade)} ${esc(h.grade)}</div></article>`;}
function page(p){const hs=[...p.histories].sort((a,b)=>String(a.date).localeCompare(String(b.date)));return `<section class="a4"><header class="page-header"><div class="title">${esc(p.group)}.Lot ${esc(p.lot)}&nbsp;&nbsp;${esc(p.name)} <span class="kana">${esc(p.kana)}</span></div><div class="meta">${esc(p.entryDivision)} / ${esc(p.team)} / ${esc(p.declaredBest)}</div></header><div class="layout"><div class="left"><section class="info"><h3>読み上げ一言</h3><div>${esc(p.readout)}</div></section><section class="info"><h3>前々回→前回</h3><div>${esc(p.previousFlow)}</div></section><section class="info"><h3>推移コメント</h3><div>${esc(p.progressComment)}</div></section></div><section class="events"><h2>出場歴</h2><div class="event-grid">${hs.map(card).join('')}</div></section></div></section>`;}
function sourcePage(){return `<section class="a4 sources"><header class="page-header"><div class="title">巻末_記録/確認元</div><div class="meta">個別ページに確認元を置かず、巻末へ集約</div></header><ol>${db.sources.map(s=>`<li><strong>${esc(s.title)}</strong><br>${esc(s.sourceType)} / 確認日:${esc(s.checkedAt)}<br>${esc(s.url)}<br>${esc(s.memo||'')}</li>`).join('')}</ol></section>`;}
function renderPages(){const p=player();$('#pages').innerHTML=page(p)+sourcePage();}
function csv(){const rows=[['player_id','group','lot','name','kana','date','competition','grade','event','class','place','status']];for(const p of db.players)for(const h of p.histories)rows.push([p.id,p.group,p.lot,p.name,p.kana,h.date,h.competitionName,h.grade,h.eventType,h.className,h.place,h.status]);return rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');}
function statusText(){const origin=dataOrigin==='local'?'ローカル編集データ':'正本DB';return `${origin} / version ${esc(db.meta?.version||'不明')} / updated ${esc(db.meta?.updatedAt||'不明')} / players ${db.players.length}`;}
function renderStatus(){ensureSafetyControls();$('#dataStatus').innerHTML=`<strong>データ状態:</strong> ${statusText()}<br><span>JSON保存はPCへ保存するだけです。GitHub上の正本DBは自動更新されません。</span>`;}
function ensureSafetyControls(){if(!$('#reloadDbBtn')){const reload=document.createElement('button');reload.id='reloadDbBtn';reload.textContent='正本DB再読込';reload.onclick=reloadRemote;const discard=document.createElement('button');discard.id='discardLocalBtn';discard.textContent='ローカル破棄';discard.onclick=discardLocal;document.querySelector('.actions')?.insertBefore(reload,$('#jsonBtn'));document.querySelector('.actions')?.insertBefore(discard,$('#jsonBtn'));}if(!$('#dataStatus')){const box=document.createElement('div');box.id='dataStatus';box.className='no-print data-status';document.querySelector('.preview')?.insertBefore(box,document.querySelector('.lock'));}}
function render(){renderList();renderPlayerForm();renderHistoryForm();renderPages();renderStatus();}
$('#search').addEventListener('input',renderList);$('#printBtn').onclick=()=>window.print();$('#jsonBtn').onclick=()=>{alert('JSON保存はPCへ保存するだけです。GitHub上の正本DBは自動更新されません。');download('database.json',JSON.stringify(db,null,2));};$('#csvBtn').textContent='Excel/CSV保存';$('#csvBtn').onclick=()=>download('histories_excel.csv',csv(),'text/csv');$('#jsonInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;db=JSON.parse(await f.text());dataOrigin='local';selectedId=db.players[0]?.id;save();};
load();
